on: push
name: Snyk
jobs:
  application:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for Python vulnerabilities
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build image
      env:
        DOCKER_BUILDKIT: 1
      run: docker build --pull -t snyky .
    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: snyky
        args: --file=Dockerfile
